-- MySQL Script generated by MySQL Workbench
-- 08/26/16 12:14:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema concesionario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concesionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concesionario` DEFAULT CHARACTER SET utf8 ;
USE `concesionario` ;

-- -----------------------------------------------------
-- Table `concesionario`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Provider` (
  `idProvider` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvider`),
  UNIQUE INDEX `idProvider_UNIQUE` (`idProvider` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Cars` (
  `idCar` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `salesPrice` FLOAT NOT NULL,
  `purchasePrice` FLOAT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `carriagePlate` VARCHAR(45) NOT NULL,
  `transmissionType` VARCHAR(45) NOT NULL,
  `chasisNumber` VARCHAR(45) NOT NULL,
  `engineNumber` VARCHAR(45) NOT NULL,
  `idProvider` INT NOT NULL,
  PRIMARY KEY (`idCar`),
  INDEX `idProvider_idx` (`idProvider` ASC),
  UNIQUE INDEX `idCar_UNIQUE` (`idCar` ASC),
  CONSTRAINT `fk_idProvider_cars`
    FOREIGN KEY (`idProvider`)
    REFERENCES `concesionario`.`Provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Profile` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Roles` (
  `RoleName` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`RoleName`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `fk_idUser_roles`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`Profile` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`Authentication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Authentication` (
  `idUser` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `lastAccess` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_idUser_authentication`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`Profile` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Sales` (
  `idSales` INT NOT NULL,
  `idClient` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idCar` INT NOT NULL,
  `totalValue` FLOAT NOT NULL,
  `qty` VARCHAR(45) NOT NULL,
  `saleType` VARCHAR(45) NULL,
  `saleDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idSales`),
  INDEX `idClient_idx` (`idClient` ASC),
  INDEX `idCar_idx` (`idCar` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  UNIQUE INDEX `idSales_UNIQUE` (`idSales` ASC),
  CONSTRAINT `fk_idClient_sales`
    FOREIGN KEY (`idClient`)
    REFERENCES `concesionario`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idCar_sales`
    FOREIGN KEY (`idCar`)
    REFERENCES `concesionario`.`Cars` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idUser_sales`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`Profile` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`Purchases` (
  `idPurchase` INT NOT NULL AUTO_INCREMENT,
  `idCar` INT NOT NULL,
  `idProvider` INT NOT NULL,
  `purchaseDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `qty` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idPurchase`),
  INDEX `idCar_idx` (`idCar` ASC),
  INDEX `idProvider_idx` (`idProvider` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  UNIQUE INDEX `idPurchase_UNIQUE` (`idPurchase` ASC),
  CONSTRAINT `fk_idCar_purchases`
    FOREIGN KEY (`idCar`)
    REFERENCES `concesionario`.`Cars` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProvider_purchases`
    FOREIGN KEY (`idProvider`)
    REFERENCES `concesionario`.`Provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idUser_purchases`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`Profile` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
