-- MySQL Script generated by MySQL Workbench
-- 09/03/16 22:05:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema concesionario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concesionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concesionario` DEFAULT CHARACTER SET utf8 ;
USE `concesionario` ;

-- -----------------------------------------------------
-- Table `concesionario`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`provider` (
  `idProvider` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvider`),
  UNIQUE INDEX `idProvider_UNIQUE` (`idProvider` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`profile` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `idCard` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`sales` (
  `idSales` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idUser` INT NOT NULL,
  `totalValue` FLOAT NOT NULL,
  `saleType` VARCHAR(45) NULL,
  `saleDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idSales`),
  INDEX `idClient_idx` (`idClient` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  UNIQUE INDEX `idSales_UNIQUE` (`idSales` ASC),
  CONSTRAINT `fk_idClient_sales`
    FOREIGN KEY (`idClient`)
    REFERENCES `concesionario`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idUser_sales`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`profile` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`cars` (
  `idCar` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `salesPrice` FLOAT NOT NULL,
  `purchasePrice` FLOAT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `carriagePlate` VARCHAR(45) NOT NULL,
  `transmissionType` VARCHAR(45) NOT NULL,
  `chasisNumber` VARCHAR(45) NOT NULL,
  `engineNumber` VARCHAR(45) NOT NULL,
  `idProvider` INT NOT NULL,
  `sold` TINYINT(1) NULL DEFAULT 0,
  `idVenta` INT NULL,
  PRIMARY KEY (`idCar`),
  INDEX `idProvider_idx` (`idProvider` ASC),
  UNIQUE INDEX `idCar_UNIQUE` (`idCar` ASC),
  INDEX `fk_idSales_cars_idx` (`idVenta` ASC),
  CONSTRAINT `fk_idProvider_cars`
    FOREIGN KEY (`idProvider`)
    REFERENCES `concesionario`.`provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idSales_cars`
    FOREIGN KEY (`idVenta`)
    REFERENCES `concesionario`.`sales` (`idSales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`roles` (
  `RoleName` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `fk_idUser_roles`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`profile` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`authentication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`authentication` (
  `idUser` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `lastAccess` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_idUser_authentication`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`profile` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionario`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`purchases` (
  `idPurchase` INT NOT NULL AUTO_INCREMENT,
  `idCar` INT NOT NULL,
  `idProvider` INT NOT NULL,
  `purchaseDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `qty` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idPurchase`),
  INDEX `idCar_idx` (`idCar` ASC),
  INDEX `idProvider_idx` (`idProvider` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  UNIQUE INDEX `idPurchase_UNIQUE` (`idPurchase` ASC),
  CONSTRAINT `fk_idCar_purchases`
    FOREIGN KEY (`idCar`)
    REFERENCES `concesionario`.`cars` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProvider_purchases`
    FOREIGN KEY (`idProvider`)
    REFERENCES `concesionario`.`provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idUser_purchases`
    FOREIGN KEY (`idUser`)
    REFERENCES `concesionario`.`profile` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
