INSERT INTO provider (companyName, phone, address, email) VALUES ("Distoyota","6430505","Av Cr70 102 2 ","distoyota@correo.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Distribuidora Autos Japon","4866633","Cr 7 B bis 126-36 ","info@distribuidoraautosjapon.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Audi Center","6439333","Avenida Calle 127 # 54A-50","diegopelaez@colwagen.com.co");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Ducati","2187777","Carrera 15 # 100-58","");
INSERT INTO provider (companyName, phone, address, email) VALUES ("HONDA","2573505","Autocedro Autopista Norte # 103 - 94","");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Dodge","6266365","Calle 140 18-47","info@dodgecolombia.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Automotores Europa","6139608","Calle 126 No 60-05","ventas@automotoreseuropa.com.co");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Daihatsu","4238300","Av El Dorado 78-20 ","info@daihatsucolombia.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Toyota","6499090","Cr7 134-36","ventas@toyota.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Hyundai","6685173","Autop Norte Cll 244","info@hyundaicol.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Peugeot","4238300","Av El Dorado 78-20 ","ventas@peugeot.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Subaru","6374354","Autop Norte 125-31","subaruventas@subaruco.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Ford","2591111","Cll 128B No 32-51","jorgecortes@ford.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Chevrolet","5700612","Av. Caracas calle 31","concesionariocaracas@chevrolet.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Mazda","5341555","Av. Carrera 70 No. 96-05","info@mazda.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Fiat","7561366","Autopista Norte N 183-58","fiatcolombia@fiat.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Jeep","6253211"," Av. Carrera 7 N 146-45","info@carcaide.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Seat","613 9608","Calle 126 # 60 - 05","ventas@automotoreseuropa.com.co");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Peugeot","4806091","Av. Boyaca No 99-96","ventas@peugeotcolombia.com");
INSERT INTO provider (companyName, phone, address, email) VALUES ("Kia","3649700","Av. 68 No 68B-91","ventas@metrokia.com");
